baseURL = "https://chanto.io/"
languageCode = "en-us"
title = "chanto"
enableRobotsTXT = true

[params]
	AuthorName = "BioMaRu"

[permalinks]
	article = "/:year/:month/:slug"
	categories = "/c/:slug/"
	tags = "/t/:slug/"

[taxonomies]
	category = "categories"
	tag = "tags"