baseURL = "https://chanto.io/"
languageCode = "en-us"
title = "Chanto"

[params]
	AuthorName = "BioMaRu"

[permalinks]
	article = "/:year/:month/:title"
	categories = "/c/:slug/"
	tags = "/t/:slug/"

[taxonomies]
	category = "categories"
	tag = "tags"